# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_profile_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildminderUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofsted_no', models.CharField(max_length=10)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
            options={
                'db_table': 'childminder_users',
            },
        ),
        migrations.CreateModel(
            name='ParentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.CharField(max_length=10)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
            options={
                'db_table': 'parent_users',
            },
        ),
    ]
