# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_childminderuser_parentuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childminderuser',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='parentuser',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_type',
        ),
        migrations.DeleteModel(
            name='ChildminderUser',
        ),
        migrations.DeleteModel(
            name='ParentUser',
        ),
    ]
