# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 20:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazard',
            name='date_to_be_completed',
            field=models.DateField(default=datetime.datetime(2017, 8, 4, 21, 39, 34, 754297)),
        ),
        migrations.AddField(
            model_name='hazard',
            name='possible_consequences',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='hazard',
            name='possible_risk',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='hazard',
            name='postControls',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hazard',
            name='preControls',
            field=models.CharField(default='', max_length=200),
        ),
    ]
