# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 12:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_auto_20170705_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='date_to_be_completed',
            field=models.DateField(default=datetime.datetime(2017, 8, 7, 13, 54, 51, 451835)),
        ),
    ]
