# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 20:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0003_auto_20170708_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='date_to_be_completed',
            field=models.DateField(default=datetime.datetime(2017, 8, 12, 21, 5, 3, 868418)),
        ),
    ]
